server.port=8080

# Maksymalna liczba zadan w kolejce BlockingQueue
integral.max-queue-size=100

# Liczba rownoleglych watkow obslugi kolejki zadan
integral.dispatcher-threads=2

spring.application.name=async
